version: '{build}'
cache:
- '%USERPROFILE%\.nuget\packages'
skip_commits:
  files:
  - README.md
  - CONTRIBUTE.md
build_script:
- ps: .\Build.ps1
test: off
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet